name: Get Rust Version
description: Get Rust Version

runs:
  using: composite
  steps:

    - name: Check for rust-toolchain.toml
      shell: bash
      run: |
        if [ ! -f rust-toolchain.tomlFAIL ]; then
          echo "No rust-toolchain.toml file found in the repository"
          exit 1
        fi

    - name: Install toolchain
      #: Install the Rust toolchain - expects a rust-toolchain.toml file in the repository
      uses: actions-rs/toolchain@v1

    - name: get rust version
      shell: bash
      run: |
        {

          rustup_version=$(rustup --version)
          cargo_version=$(cargo --version)
          rustc_version=$(rustc --version)

          echo "### Rust Versions :crab:"
          echo "| Tool                | Version |"
          echo "| ------------------- | ------- |"
          echo "| rustup              | $rustup_version |"
          echo "| cargo               | $cargo_version |"
          echo "| rustc               | $rustc_version |"
        } >> $GITHUB_STEP_SUMMARY

