name: Test Github Summary

on: [push]

jobs:
  sum_up_things:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Get Rust Version
        id: get-rust-version
        run: |
          echo "rustup_version=$(rustup --version)" >> $GITHUB_STEP_SUMMARY
          echo "cargo_version=$(cargo --version)" >> $GITHUB_STEP_SUMMARY
          echo "rustc_version=$(rustc --version)" >> $GITHUB_STEP_SUMMARY

