name: Test Github Summary

on: [push]

jobs:
  sum_up_things:
    runs-on: ${{ matrix.os }}  # Runs on Ubuntu and Windows as defined in the matrix

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]  # Define the operating systems for the matrix
  
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name : Get Rust Version
        uses: ./.github/actions/get-rust-version
